"""Regime classifier — both quant and categorical.

This is the most differentiated piece of AlphaFactory's custom layer. Every
signal generated by a strategy must be tagged with the regime active at the
signal's bar; backtest reports slice P&L by regime; live strategies are
gated to fire only inside their allowed regimes.

Two parallel systems:

A. **Quant regime** — orthogonal trend × volatility grid.

   Trend bucket from ADX:
       ADX < `adx_range_max`           → "range"
       `adx_range_max` ≤ ADX < `adx_strong_min` → "weak_trend"
       ADX ≥ `adx_strong_min`          → "strong_trend"

   Volatility bucket from rolling ATR percentile (default 100 bars):
       bottom third  → "low"
       middle third  → "medium"
       top third     → "high"

   Cross → 9 regimes, e.g. ``range_low``, ``weak_trend_high``, etc.

B. **Categorical state** (AlphaTeam mental model):
       - "consolidating"  — range-bound, stable ATR, structure within bounds
       - "directional"    — sustained slope, ATR not collapsing, structure stepping
       - "chaotic"        — neither holds; volatility unstable, no clear structure

   Used as a hard gate: if state == "chaotic", **no trade**, period.

The classifier reads pre-computed ATR + ADX columns rather than recomputing
them, so it composes cleanly with the indicator pipeline.

No lookahead: every regime tag at bar T uses only data ``<= T``.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

import polars as pl

from src.features.adx import adx as compute_adx
from src.features.atr import atr as compute_atr

TrendBucket = Literal["range", "weak_trend", "strong_trend"]
VolBucket = Literal["low", "medium", "high"]
CategoricalState = Literal["consolidating", "directional", "chaotic"]


@dataclass(frozen=True)
class RegimeConfig:
    """Tunable thresholds for the regime classifier.

    Defaults are AlphaTeam-style starting points; tune per instrument
    via walk-forward analysis, not by eye.
    """

    # --- Trend buckets (ADX) ---
    adx_period: int = 14
    adx_range_max: float = 20.0
    adx_strong_min: float = 40.0

    # --- Volatility buckets (ATR percentile rank) ---
    atr_period: int = 14
    atr_percentile_window: int = 100
    vol_low_pct: float = 1.0 / 3.0
    vol_high_pct: float = 2.0 / 3.0

    # --- Categorical state thresholds ---
    structure_window: int = 20
    # If close-to-close slope over `structure_window` exceeds this many ATRs,
    # consider it directional.
    directional_slope_atr: float = 1.5
    # If rolling ATR stddev / mean exceeds this, ATR is unstable → chaotic.
    atr_instability_threshold: float = 0.6
    # If range width over `structure_window` < this many ATRs, it's a tight
    # consolidation.
    consolidation_range_atr: float = 3.0


def add_quant_regime(
    df: pl.DataFrame,
    *,
    cfg: RegimeConfig | None = None,
) -> pl.DataFrame:
    """Append ``trend_bucket``, ``vol_bucket``, ``quant_regime`` columns.

    The frame must contain ``adx`` and ``atr`` columns already, OR they will
    be computed using ``cfg``'s periods.
    """
    cfg = cfg or RegimeConfig()

    if "adx" not in df.columns:
        df = compute_adx(df, period=cfg.adx_period)
    if "atr" not in df.columns:
        df = compute_atr(df, period=cfg.atr_period)

    trend_expr = (
        pl.when(pl.col("adx") < cfg.adx_range_max)
        .then(pl.lit("range"))
        .when(pl.col("adx") < cfg.adx_strong_min)
        .then(pl.lit("weak_trend"))
        .otherwise(pl.lit("strong_trend"))
        .alias("trend_bucket")
    )

    # Rolling percentile rank of ATR over the lookback window. We use
    # `rolling_map` would be slow; instead, rank ATR by counting how many
    # prior-window values it exceeds, then divide.
    pct_rank = (
        pl.col("atr")
        .rolling_map(
            lambda s: (s.rank(method="average").tail(1) / s.len()).to_list()[0]
            if s.len() > 0
            else None,
            window_size=cfg.atr_percentile_window,
            min_periods=cfg.atr_percentile_window,
        )
        .alias("_atr_pct")
    )

    df = df.with_columns(pct_rank, trend_expr)

    vol_expr = (
        pl.when(pl.col("_atr_pct").is_null())
        .then(None)
        .when(pl.col("_atr_pct") <= cfg.vol_low_pct)
        .then(pl.lit("low"))
        .when(pl.col("_atr_pct") <= cfg.vol_high_pct)
        .then(pl.lit("medium"))
        .otherwise(pl.lit("high"))
        .alias("vol_bucket")
    )

    df = df.with_columns(vol_expr)

    quant_regime = (
        pl.when(pl.col("vol_bucket").is_null() | pl.col("adx").is_null())
        .then(None)
        .otherwise(pl.col("trend_bucket") + "_" + pl.col("vol_bucket"))
        .alias("quant_regime")
    )

    return df.with_columns(quant_regime).drop("_atr_pct")


def add_categorical_state(
    df: pl.DataFrame,
    *,
    cfg: RegimeConfig | None = None,
) -> pl.DataFrame:
    """Append a ``categorical_state`` column.

    Logic (each evaluated per bar T over the last ``structure_window`` bars):

    * ``directional`` if |close_T - close_{T-W}| > directional_slope_atr * ATR_T
      AND rolling ATR std/mean ≤ atr_instability_threshold.
    * ``consolidating`` if (high_max - low_min) < consolidation_range_atr * ATR_T
      AND rolling ATR std/mean ≤ atr_instability_threshold.
    * ``chaotic`` otherwise — including when ATR is too unstable to classify.

    Edge cases:

    * If both directional and consolidating conditions match (shouldn't
      happen mathematically given the thresholds, but possible with edge
      params), directional wins — slope is the stronger signal.
    * The first ``structure_window`` bars produce a ``chaotic`` tag because
      we cannot evaluate structure; the strategy's regime gate should
      treat unclassifiable as "do not trade".
    """
    cfg = cfg or RegimeConfig()
    w = cfg.structure_window

    if "atr" not in df.columns:
        df = compute_atr(df, period=cfg.atr_period)

    rolling_high = pl.col("high").rolling_max(window_size=w)
    rolling_low = pl.col("low").rolling_min(window_size=w)
    range_width = rolling_high - rolling_low
    close_slope = (pl.col("close") - pl.col("close").shift(w)).abs()

    atr_std = pl.col("atr").rolling_std(window_size=w)
    atr_mean = pl.col("atr").rolling_mean(window_size=w)
    atr_cv = (
        pl.when(atr_mean > 0)
        .then(atr_std / atr_mean)
        .otherwise(None)
    )

    is_directional = (close_slope > cfg.directional_slope_atr * pl.col("atr")) & (
        atr_cv <= cfg.atr_instability_threshold
    )
    is_consolidating = (range_width < cfg.consolidation_range_atr * pl.col("atr")) & (
        atr_cv <= cfg.atr_instability_threshold
    )

    state_expr = (
        pl.when(pl.col("atr").is_null() | atr_cv.is_null())
        .then(pl.lit("chaotic"))
        .when(is_directional)
        .then(pl.lit("directional"))
        .when(is_consolidating)
        .then(pl.lit("consolidating"))
        .otherwise(pl.lit("chaotic"))
        .alias("categorical_state")
    )

    return df.with_columns(state_expr)


def classify_regimes(
    df: pl.DataFrame,
    *,
    cfg: RegimeConfig | None = None,
) -> pl.DataFrame:
    """Convenience: run both classifiers in one shot.

    Returns the input frame with these added columns:
        adx, plus_di, minus_di       (if not present)
        atr                          (if not present)
        trend_bucket
        vol_bucket
        quant_regime
        categorical_state
    """
    cfg = cfg or RegimeConfig()
    df = add_quant_regime(df, cfg=cfg)
    df = add_categorical_state(df, cfg=cfg)
    return df
